"""
    Creation Date Model
    exports class:CreatedAt
    generated by: Bryan Nilsen
"""
from django.db import models


class CreatedAt(models.Model):
    """
    Creates and stores the date and time when new object is created.
    """
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
