"""
    OrderProduct Model
    exports class: OrderProduct
    generated by: Bryan Nilsen
"""
from django.db import models
from .order import Order
from .product import Product


class OrderProduct(models.Model):
    """
    Stores the relationship between an order and product.
    Related Data: Order, Product
    """

    # Related Data
    order = models.ForeignKey(
        Order, on_delete=models.DO_NOTHING, related_name="order_products")
    product = models.ForeignKey(
        Product, on_delete=models.DO_NOTHING, related_name="order_products")

    class Meta:
        verbose_name = ("order_product")
        verbose_name_plural = ("order_products")

    def __str__(self):
        return f'OrderProduct No. {self.id}'
