"""
    Payment Type Model
    exports class:PaymentType
    generated by: Bryan Nilsen
"""
from django.db import models
from .createdat import CreatedAt
from .customer import Customer


class PaymentType(CreatedAt):
    """
    Stores the properties of a single payment type.
    Inherits: created_at from CreatedAt class
    Related Data: Customer
    """

    merchant_name = models.CharField(max_length=25)
    account_number = models.CharField(max_length=25)
    expiration_date = models.DateField()

    # Related Data
    customer = models.ForeignKey(
        Customer, on_delete=models.DO_NOTHING, related_name="payment")

    class Meta:
        verbose_name = ("payment_type")
        verbose_name_plural = ("payment_types")

    def __str__(self):
        return self.merchant_name
