"""
    Product Model
    exports class:Product
    generated by: Bryan Nilsen
"""
from django.db import models
from .createdat import CreatedAt
from .producttype import ProductType
from .customer import Customer


class Product(CreatedAt):
    """
    Stores the properties of a single product.
    Related Data: Customer, ProductType
    Inherits: created_at from CreatedAt class
    """

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    location = models.CharField(max_length=75)
    image_path = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()

    # Related Data
    producttype = models.ForeignKey(
        ProductType, on_delete=models.DO_NOTHING, related_name="products")
    customer = models.ForeignKey(
        Customer, on_delete=models.DO_NOTHING, related_name="products")

    class Meta:
        verbose_name = ("product")
        verbose_name_plural = ("products")

    def __str__(self):
        return self.name
